#!/usr/bin/env bash
source ./config/settings

# validate user input
if [[ $# -ne 2 ]]; then
  echo
  echo "Wrong number of parameters. Usage: ./simon-says [create-stack|delete-stack] [test|prod]"
  echo
  exit 1
fi

# constants
CREATE_STACK=create-stack
DELETE_STACK=delete-stack

if [[ $1 == $CREATE_STACK ]]; then            # create stack
  (cd ./scripts && \
   ./01-create-s3-bucket $2 && \
   ./02-build-and-upload-lambda $2 && \
   ./03-create-lambda-infrastructure $2)
elif [[ $1 == $DELETE_STACK ]]; then          # delete stack
  (cd ./scripts &&./99-delete-stack $2)
else                                          # error message
  echo
  echo "Unknown command '$1'. Valid commands: [create-stack|delete-stack] "
  echo
fi
