#!/usr/bin/env bash
source ./config/settings

function createLambdaFunctions() {
  ENV=$1
  for FUNCTION_NAME in $FUNCTION_CREATE_MESSAGE_NAME $FUNCTION_REGISTER_USER_NAME
  do
    ./02-build-and-upload-lambda $ENV $FUNCTION_NAME
  done
}

# validate user input
if [[ $# -lt 2 ]]; then
  echo
  echo "Wrong number of parameters. Usage: ./simon-says [create-stack|delete-stack] [test|prod]"
  echo
  exit 1
fi

# create stack
if [[ $1 == $CREATE_STACK ]]; then
  (cd ./scripts && \
   ./01-create-s3-bucket $2 && \
   createLambdaFunctions $2 && \
   ./03-create-lambda-infrastructure $2)

# delete stack
elif [[ $1 == $DELETE_STACK ]]; then
  (cd ./scripts &&./99-delete-stack $2)

# update stack
elif [[ $1 == $UPDATE_STACK ]]; then
  (cd ./scripts &&./04-update-lambda-infrastructure $2)

# update functions
elif [[ $1 == $UPDATE_FUNCTION ]]; then
  (cd ./scripts &&./05-update-lambda-function $2 $3)

# error message otherwise
else
  echo
  echo "Unknown command '$1'. Valid commands: [create-stack|delete-stack] "
  echo
fi
