#!/usr/bin/env bash
source ../../../config/settings

# validate user input
if [[ $# -ne 1 ]]; then
  echo
  echo "Wrong number of parameters. Usage: ./build_and_update [test|prod]"
  echo
  exit 1
fi

# install dependencies
go get -d ./...

# compile Go
GOARCH=amd64 GOOS=linux go build -o $FUNCTION_REGISTER_USER

# change permissions
chmod u+x $FUNCTION_REGISTER_USER

# zip executable
zip $FUNCTION_REGISTER_USER.zip $FUNCTION_REGISTER_USER

# upload zip to S3 - it's not required but at least everything is consistent
aws --profile $AWS_PROFILE s3 cp $FUNCTION_REGISTER_USER.zip s3://$BUCKET_NAME_PREFIX-$1/

# update lambda function
aws --profile $AWS_PROFILE lambda update-function-code --function-name RegisterUser --s3-bucket $BUCKET_NAME_PREFIX-$1 --s3-key $FUNCTION_REGISTER_USER.zip --publish

# cleanup
rm $FUNCTION_REGISTER_USER $FUNCTION_REGISTER_USER.zip

# test call
aws --profile sideprojects lambda invoke --function-name RegisterUser response.json

# print response
echo
cat response.json
echo
