#!/usr/bin/env bash
source ../../../config/settings

# validate user input
if [[ $# -ne 1 ]]; then
  echo
  echo "Wrong number of parameters. Usage: ./build_and_deploy [test|prod]"
  echo
  exit 1
fi

# install dependencies
go get -d ./...

# compile Go
GOARCH=amd64 GOOS=linux go build -o $FUNCTION_REGISTER_USER

# change permissions
chmod u+x $FUNCTION_REGISTER_USER

# zip executable
zip $FUNCTION_REGISTER_USER.zip $FUNCTION_REGISTER_USER

# remove executable
rm $FUNCTION_REGISTER_USER

# upload zip to S3
aws --profile $AWS_PROFILE s3 cp $FUNCTION_REGISTER_USER.zip s3://$BUCKET_NAME_PREFIX-$1/
