#!/usr/bin/env bash
source ../../../config/settings

# validate user input
if [[ $# -ne 1 ]]; then
  echo
  echo "Wrong number of parameters. Usage: ./build_and_update [test|prod]"
  echo
  exit 1
fi

# install dependencies
#go get -d ./...

# constant(s)
FUNCTION_NAME="create-message"

# compile Go
GOARCH=amd64 GOOS=linux go build -o $FUNCTION_NAME

# change permissions
chmod u+x $FUNCTION_NAME

# zip executable
zip $FUNCTION_NAME.zip $FUNCTION_NAME

# upload zip to S3 - it's not required but at least everything is consistent
aws --profile $AWS_PROFILE s3 cp $FUNCTION_NAME.zip s3://$BUCKET_NAME_PREFIX-$1/

# update lambda function
aws --profile $AWS_PROFILE lambda update-function-code --function-name CreateMessage --s3-bucket $BUCKET_NAME_PREFIX-$1 --s3-key $FUNCTION_NAME.zip --publish
#aws --profile $AWS_PROFILE lambda update-function-code --function-name CreateMessage --zip-file fileb://$FUNCTION_NAME.zip

# cleanup
rm $FUNCTION_NAME $FUNCTION_NAME.zip
