#!/usr/bin/env bash

# validate user input
if [[ $# -ne 1 ]]; then
  echo
  echo "Wrong number of parameters. Usage: ./01-create-s3-bucket [test|prod]"
  echo
  exit 1
fi

aws --profile $AWS_PROFILE s3 mb s3://geobricks-serverless-chat-$1
