#!/usr/bin/env bash
source ./goodies

# validate user input
if [[ $# -ne 1 ]]; then
  printCreateStackHelp
  exit 1
fi

aws --profile sideprojects \
    cloudformation create-stack \
    --stack-name lambda-repository-$1-stack \
    --template-body file://../infrastructure/lambda-repository/stack.yml \
    --parameters file://../infrastructure/lambda-repository/parameters-$1.json \
    --region ap-southeast-2 \
    --capabilities CAPABILITY_NAMED_IAM
