#!/usr/bin/env bash
set -e

# validate user input
if [[ $# -ne 2 ]]; then
  echo
  echo "Wrong number of parameters. Usage: ./02-build-and-upload-lambda [test|prod] [CreateMessage|RegisterUser]"
  echo
  exit 1
fi

# change directory according to the function
if [[ $2 == "$FUNCTION_CREATE_MESSAGE_NAME" ]]; then
  DIR="../functions/messages/create/"
elif [[ $2 == "$FUNCTION_REGISTER_USER_NAME" ]]; then
  DIR="../functions/users/register/"
elif [[ $2 == "$FUNCTION_RETRIEVE_MESSAGES_NAME" ]]; then
  DIR="../functions/messages/retrieve/"
fi
cd $DIR

# install dependencies
go get -d ./...

# compile Go
GOARCH=amd64 GOOS=linux go build -o "$2"

# change permissions
chmod u+x "$2"

# zip executable
zip "$2".zip "$2"

# upload zip to S3
aws --profile "$AWS_PROFILE" s3 cp "$2".zip s3://"$BUCKET_NAME_PREFIX"-"$1"/

# cleanup
rm "$2".zip "$2"
