#!/usr/bin/env bash
source ../config/settings

# validate user input
if [[ $# -ne 1 ]]; then
  echo
  echo "Wrong number of parameters. Usage: ./02-build-and-upload-lambda [test|prod]"
  echo
  exit 1
fi

(cd ../functions/messages/create/ && ./build_and_deploy $1)
