#!/usr/bin/env bash
source ./goodies

stackStatus() {
  aws --profile sideprojects cloudformation describe-stacks --stack-name $1
}

# validate user input
if [[ $# -ne 1 ]]; then
  printCreateStackHelp
  exit 1
fi

AWS_OUTPUT=$(aws --profile sideprojects cloudformation create-stack --stack-name lambda-infrastructure-$1-stack --template-body file://../infrastructure/lambda-infrastructure/stack.yml --parameters file://../infrastructure/lambda-infrastructure/parameters-$1.json --region ap-southeast-2 --capabilities CAPABILITY_NAMED_IAM)
STACK_ARN=$(echo $AWS_OUTPUT | jq ".StackId")
CLEAN_ARN=$(echo $STACK_ARN | sed 's/\"//g')
STACK_STATUS=$(stackStatus $CLEAN_ARN | jq ".Stacks[0].StackStatus")
CREATE_COMPLETE="\"CREATE_COMPLETE\""
ROLLBACK_COMPLETE="\"ROLLBACK_COMPLETE\""

echo "STACK ARN........: $CLEAN_ARN"
while [ $STACK_STATUS != $CREATE_COMPLETE ] && [ $STACK_STATUS != $ROLLBACK_COMPLETE ]; do
  echo "CURRENT STATUS...: $STACK_STATUS, WAIT 5s..."
  sleep 5
  STACK_STATUS=$(stackStatus $CLEAN_ARN | jq ".Stacks[0].StackStatus")
done

echo
echo "STACK CREATION COMPLETED WITH STATUS: $STACK_STATUS"
