#!/usr/bin/env bash
source ../config/settings

# validate user input
if [[ $# -ne 1 ]]; then
  echo
  echo "Wrong number of parameters. Usage: ./99-delete-stack [test|prod]"
  echo
  exit 1
fi

# empty and delete bucket(s)
aws --profile sideprojects s3 rb s3://$BUCKET_NAME_PREFIX-$1 --force

# remove stack
aws --profile sideprojects \
    cloudformation delete-stack \
    --stack-name $LAMBDA_INFRASTRUCTURE_STACK_NAME_PREFIX-$1 \
