#!/usr/bin/env bash
set -e
source ../config/settings

stackStatus() {
  aws --profile $AWS_PROFILE cloudformation describe-stacks --stack-name $1
}

# validate user input
if [[ $# -ne 1 ]]; then
  echo
  echo "Wrong number of parameters. Usage: ./99-delete-stack [test|prod]"
  echo
  exit 1
fi

# empty and delete bucket(s)
aws --profile $AWS_PROFILE s3 rb s3://$BUCKET_NAME_PREFIX-$1 --force

# remove stack
aws --profile $AWS_PROFILE \
    cloudformation delete-stack \
    --stack-name $LAMBDA_INFRASTRUCTURE_STACK_NAME_PREFIX-$1
