#!/usr/bin/env bash
source ./goodies

# validate user input
if [[ $# -ne 1 ]]; then
  printDeleteStackHelp
  exit 1
fi

# empty bucket(s)
aws --profile sideprojects s3 rm s3://geobricks-serverless-chat-$1/ --recursive

# remove stack
aws --profile sideprojects \
    cloudformation delete-stack \
    --stack-name lambda-repository-$1-stack \

# remove stack
aws --profile sideprojects \
    cloudformation delete-stack \
    --stack-name lambda-infrastructure-$1-stack \
