#!/usr/bin/env bash
source ../../config/settings

# validate user input
if [[ $# -ne 1 ]]; then
  echo
  echo "Wrong number of parameters. Usage: ./build_and_deploy [test|prod]"
  echo
  exit 1
fi

# install dependencies
go get -d ./...

# constant(s)
FUNCTION_NAME="retrieve-potatoes"

# compile Go
GOARCH=amd64 GOOS=linux go build -o $FUNCTION_NAME

# zip executable
zip $FUNCTION_NAME.zip $FUNCTION_NAME

# remove executable
rm $FUNCTION_NAME

# upload zip to S3
aws --profile $AWS_PROFILE s3 cp $FUNCTION_NAME.zip s3://$BUCKET_NAME_PREFIX-$1/
